export enum POPUP_TYPE {
  SITE = 'SITE',
  SHIP = 'SHIP',
  BMS = 'BMS',
  USER = 'USER',
  SHIP_MATCHING = 'SHIP_MATCHING',
  SHIP_MATCHINGADD = 'SHIP_MATCHINGADD',
  BMS_MODEL = 'BMS_MODEL',
  FOLDER = 'FOLDER',
  FILE = 'FILE',
  VERSION_MAIN = 'VERSION_MAIN',    // 좀 넓게 표출
  VERSION = 'VERSION',
}
